name: Docker Build and Push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Auth to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          gcloud_service_key: ${{ secrets.GCP_SA }}
          registry: gcr.io
          project_id: devops-283720
          image_name: gcr.io/devops-283720/fasterapi
          image_tag: ${{ github.sha }},latest
          dockerfile: ./fasterapi/Dockerfile
          context: ./fasterapi
  