name: Delete Preview Environment

on:
  pull_request:
    types:
      - closed
    branches:
      - 'feature/**'

env:
  GKE_PROJECT: devops-283720
  GKE_CLUSTER: autopilot-cluster-1
  GKE_LOCATION: us-west1

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA }}

      - uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}

      - uses: google-github-actions/get-gke-credentials@v1.0.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          project_id: ${{ env.GKE_PROJECT }}
          location: ${{ env.GKE_LOCATION }}

      - uses: azure/setup-helm@v3
        with:
          version: 'latest'
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Slugify
        uses: rlespinasse/github-slug-action@v4.4.0

      - name: Delete Helm Chart
        run: helm uninstall -n ${{ env.GITHUB_REF_SLUG_URL }} fasterapi
        working-directory: charts

      - name: Delete Namespace
        run: kubectl delete ns ${{ env.GITHUB_REF_SLUG_URL }}
